# Generated by Django 4.2.1 on 2023-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('bold_word1', models.CharField(max_length=30, verbose_name='Bold Word 1')),
                ('bold_word2', models.CharField(max_length=30, verbose_name='Bold Word 2')),
                ('subtitle', models.CharField(max_length=100, verbose_name='SubTitle')),
                ('btn_name', models.CharField(max_length=50, verbose_name='Button Name')),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Subtitle')),
            ],
        ),
    ]
