# Generated by Django 4.2.1 on 2023-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_home_bold_word1_alter_home_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='subtitle',
            field=models.TextField(verbose_name='SubTitle'),
        ),
    ]
