# Generated by Django 4.2.1 on 2023-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_home_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='subtitle',
            field=models.CharField(max_length=80, verbose_name='Subtitle'),
        ),
    ]
