# Generated by Django 4.2.1 on 2023-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_homecontent_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='images', verbose_name='Image 1')),
                ('title1', models.CharField(max_length=80, verbose_name='Title 1')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('img2', models.ImageField(upload_to='images', verbose_name='Image 2')),
                ('title2', models.CharField(max_length=80, verbose_name='Title 2')),
                ('text2', models.TextField(verbose_name='Text 2')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
