# Generated by Django 4.2.1 on 2023-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_testimonial_testimonialcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlanContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('position', models.BooleanField(verbose_name='Top Or Bottom')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('offer1', models.CharField(max_length=100, verbose_name='Offer 1')),
                ('offer2', models.CharField(max_length=100, verbose_name='Offer 2')),
                ('offer3', models.CharField(max_length=100, verbose_name='Offer 3')),
                ('offer4', models.CharField(max_length=100, verbose_name='Offer 4')),
                ('offer5', models.CharField(max_length=100, verbose_name='Offer 5')),
                ('offer6', models.CharField(max_length=100, verbose_name='Offer 6')),
            ],
        ),
    ]
