# Generated by Django 4.2.1 on 2023-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pricingplan_pricingplancontent_pricingplanoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplanoffer',
            name='offer1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Offer 1'),
        ),
        migrations.AlterField(
            model_name='pricingplanoffer',
            name='offer2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Offer 2'),
        ),
        migrations.AlterField(
            model_name='pricingplanoffer',
            name='offer3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Offer 3'),
        ),
        migrations.AlterField(
            model_name='pricingplanoffer',
            name='offer4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Offer 4'),
        ),
        migrations.AlterField(
            model_name='pricingplanoffer',
            name='offer5',
            field=models.CharField(blank=True, max_length=100, verbose_name='Offer 5'),
        ),
        migrations.AlterField(
            model_name='pricingplanoffer',
            name='offer6',
            field=models.CharField(blank=True, max_length=100, verbose_name='Offer 6'),
        ),
    ]
