# Generated by Django 4.2.1 on 2023-05-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_pricingplancontent_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
            options={
                'verbose_name': 'Blog Entries',
                'verbose_name_plural': 'Blog Entries',
            },
        ),
        migrations.CreateModel(
            name='BlogEntriesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
