# Generated by Django 4.2.1 on 2023-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_blogentries_blogentriescontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('text3', models.TextField(verbose_name='Text 3')),
                ('placeholder1', models.CharField(max_length=50, verbose_name='Placeholder 1')),
                ('placeholder2', models.CharField(max_length=50, verbose_name='Placeholder 2')),
                ('placeholder3', models.CharField(max_length=50, verbose_name='Placeholder 3')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
            options={
                'verbose_name': 'Contact GET',
                'verbose_name_plural': 'Contact GET',
            },
        ),
    ]
