# Generated by Django 4.2.1 on 2023-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contactpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social1', models.CharField(max_length=50, verbose_name='Social 1')),
                ('social_url1', models.URLField(verbose_name='Social Url 1')),
                ('social2', models.CharField(max_length=50, verbose_name='Social 2')),
                ('social_url2', models.URLField(verbose_name='Social Url 2')),
                ('social3', models.CharField(max_length=50, verbose_name='Social 3')),
                ('social_url3', models.URLField(verbose_name='Social Url 3')),
                ('social4', models.CharField(max_length=50, verbose_name='Social 4')),
                ('social_url4', models.URLField(verbose_name='Social Url 4')),
                ('social5', models.CharField(max_length=50, verbose_name='Social 5')),
                ('social_url5', models.URLField(verbose_name='Social Url 5')),
                ('copyright1', models.CharField(max_length=200, verbose_name='Copyright')),
            ],
        ),
    ]
