# Generated by Django 4.2.1 on 2023-05-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
    ]
